In [1]:
!pip install attacut

     |████████████████████████████████| 1.3 MB 26.9 MB/s 
     |████████████████████████████████| 596 kB 46.7 MB/s 
     |████████████████████████████████| 473 kB 63.4 MB/s 
     |████████████████████████████████| 87 kB 7.0 MB/s 
     |████████████████████████████████| 45 kB 3.0 MB/s 
     |████████████████████████████████| 743 kB 34.4 MB/s 
  Created wheel for fire: filename=fire-0.4.0-py2.py3-none-any.whl size=115942 sha256=b2903188cc452dec41008937a4bc51b8877ae6895806443ac3002f77cb75d4ae
  Stored in directory: /root/.cache/pip/wheels/8a/67/fb/2e8a12fa16661b9d5af1f654bd199366799740a85c64981226
Successfully built fire
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from attacut import tokenize

In [3]:
tokenize('ฉันหิวข้าว')

['ฉัน', 'หิว', 'ข้าว']

In [4]:
Xtrain = ['“บิ๊กตู่” ให้กำลังใจ จนท.บำราศนราดูร ขอหนักนิดเบาหน่อยพูดกันดีๆ พร้อมปรับแก้',
          'รัฐบาลไฟเขียวต่ออายุราชการ อธิบดีกรมอุทยานแห่งชาติฯ อีก 1 ปี',
          '“บิ๊กป้อม” รับปากเคลียร์ “สิระ-ไผ่” ปะทะเดือดไลน์ พปชร.ยันทำงานกับ ปชป.ได้',
          'จ่อเซ็นแมนฯยู!! “จู๊ด เบลลิงแฮม” วันเดอร์คิดเบอร์มิงแฮม พร้อมครอบครัวบุกสนามซ้อมแคร์ริงตัน',
          '“จิ้งจอก” เลิกบู่ “วาร์ดี-บาร์นส” คนละ 2 เม็ด ถลุงวิลล่ายับ 4-0',
          '“ลิเวอร์พูล” นับถอยหลัง 5 วัน ฉลองแชมป์ที่บ้าน “เอฟเวอร์ตัน”'
          ]
Ytrain = ['การเมือง',
          'การเมือง',
          'การเมือง',
          'กีฬา',
          'กีฬา',
          'กีฬา'
          ]
Xtest = ['“อิทธิพล” ยัน คน พปชร.พี่น้องกัน เคลียร์กันได้ หลังไลน์เดือดปมหน้ากาก',
         '“บิ๊กป้อม” รับปากเคลียร์ “สิระ-ไผ่” ปะทะเดือดไลน์ พปชร.ยันทำงานกับ ปชป.ได้',
         '“ลิเวอร์พูล” นับถอยหลัง 5 วัน ฉลองแชมป์ที่บ้าน “เอฟเวอร์ตัน”',
         'เงินเหลือๆ “ฟลอยด์” ปล่อยวาทะเด็ดพร้อมฮุบกิจการ “นิวคาสเซิล”']

In [5]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [6]:
count_vect = CountVectorizer(tokenizer=tokenize)

In [7]:
Xtrain_count = count_vect.fit_transform(Xtrain)

In [8]:
Xtrain_count.shape

(6, 85)

In [9]:
Xtrain_count[0].toarray()

array([[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1]])

In [10]:
tf_transformer = TfidfTransformer(use_idf=False)

In [11]:
tf_transformer.fit(Xtrain_count)

TfidfTransformer(use_idf=False)

In [12]:
Xtrain_tf = tf_transformer.transform(Xtrain_count)

In [13]:
Xtrain_tf.shape

(6, 85)

In [14]:
Xtrain_tf[0].toarray()

array([[0.69631062, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17407766, 0.        , 0.17407766, 0.17407766,
        0.        , 0.        , 0.        , 0.        , 0.17407766,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17407766, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.17407766,
        0.17407766, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17407766, 0.        , 0.        , 0.        ,
        0.17407766, 0.17407766, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.17407766, 0.17407766, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
clf = MultinomialNB()

In [17]:
clf.fit(Xtrain_tf, Ytrain)

MultinomialNB()

In [18]:
Xtest_count = count_vect.transform(Xtest)

In [19]:
Xtest_tf = tf_transformer.transform(Xtest_count)

In [21]:
clf.predict(Xtest_tf)

array(['การเมือง', 'การเมือง', 'กีฬา', 'กีฬา'], dtype='<U8')

In [23]:
import pandas as pd

In [24]:
url = 'https://nriis.go.th/temp/rgroup.csv'
df = pd.read_csv(url)

In [25]:
df.count()

การแพทย์                                                            14877
13                                                                  14877
ประสบการณ์ของมารดาเกี่ยวกับภาวะไข้กับการจัดการภาวะไข้ของบุตร        14877
Mother's Experience on Fever and Fever Management in Young Chile    14848
NULL                                                                 6214
NULL.1                                                               5257
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14877 entries, 0 to 14876
Data columns (total 6 columns):
 #   Column                                                            Non-Null Count  Dtype 
---  ------                                                            --------------  ----- 
 0   การแพทย์                                                          14877 non-null  object
 1   13                                                                14877 non-null  int64 
 2   ประสบการณ์ของมารดาเกี่ยวกับภาวะไข้กับการจัดการภาวะไข้ของบุตร      14877 non-null  object
 3   Mother's Experience on Fever and Fever Management in Young Chile  14848 non-null  object
 4   NULL                                                              6214 non-null   object
 5   NULL.1                                                            5257 non-null   object
dtypes: int64(1), object(5)
memory usage: 697.5+ KB


In [40]:
df['การแพทย์']

0        การแพทย์
1        การแพทย์
2        การแพทย์
3        การแพทย์
4        การแพทย์
           ...   
14872       สังคม
14873       สังคม
14874       สังคม
14875       สังคม
14876       สังคม
Name: การแพทย์, Length: 14877, dtype: object

In [41]:
df['ประสบการณ์ของมารดาเกี่ยวกับภาวะไข้กับการจัดการภาวะไข้ของบุตร']

0        การเพิ่มประสิทธิภาพในการพาดีเอ็นเอเข้าสู่เซลล์...
1        การดื่มสุราเป็นปัจจัยเสี่ยงของมะเร็งลำไส้ใหญ่แ...
2        แนวทางในการแก้ปัญหาของระบบท่อภายในอาคารที่ใช้ส...
3        บทบาทของสารไฟโตเอสโตรเจนต่อการเปลี่ยนแปลงระบบฟ...
4        การตรวจหาไวรัสก่อโรคภูมิคุ้มกันบกพร่อง (HIV) ท...
                               ...                        
14872    คุณภาพชีวิตของนักเรียนมัธยมศึกษาในพื้นที่สามจั...
14873    การศึกษาปัญหาและแนวทางแก้ไขเด็กไร้สถานะในจังหว...
14874    การใช้เงินในกองทุนเงินทดแทนและกองทุนประกันสังค...
14875    การจัดทำยุทธศาสตร์การพัฒนาเมืองพัทยาให้เป็นเมื...
14876    การบริหารจัดการมรดกทางวัฒนธรรมในศาสนสถานและสถา...
Name: ประสบการณ์ของมารดาเกี่ยวกับภาวะไข้กับการจัดการภาวะไข้ของบุตร, Length: 14877, dtype: object

In [42]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [43]:
count_vect = CountVectorizer(tokenizer=tokenize)

In [44]:
Xtrain_count = count_vect.fit_transform(df['ประสบการณ์ของมารดาเกี่ยวกับภาวะไข้กับการจัดการภาวะไข้ของบุตร'])

In [45]:
Xtrain_count.shape

(14877, 13926)

In [46]:
Xtrain_count[0].toarray()

array([[0, 4, 0, ..., 0, 0, 0]])

In [47]:
tf_transformer = TfidfTransformer(use_idf=False)

In [48]:
Xtrain_tf = tf_transformer.transform(Xtrain_count)

In [49]:
Xtrain_tf.shape

(14877, 13926)

In [118]:
Xtrain_tf[0].toarray()

array([[0.       , 0.6172134, 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [107]:
from sklearn.naive_bayes import MultinomialNB

In [52]:
clf = MultinomialNB()

In [96]:
clf.fit(Xtrain_tf, df['การแพทย์'])

MultinomialNB()

In [120]:
Xtest_count = count_vect.transform([
"การตรวจหาไวรัสก่อโรคภูมิคุ้มกันบกพร่อง (HIV) ที่ดื้อต่อยาต้านไวรัส โดยใช้ oligonucleotide probe",
"ปัญหาและความต้องการฟื้นฟูเยียวยาในมิติทางด้านเศรษฐกิจครัวเรือน, มิติทางด้านสภาพแวดล้อม และมิติทางด้านสังคม",
"เปรียบเทียบการเจริญเติบโตและการให้ผลผลิตของปาล์มน้ำมันที่ได้จากการเพาะเลี้ยง เนื้อเยื่อ 6 สายพันธุ์ ในพื้นที่ดินทรายชายฝั่งทะเล ณ มหาวิทยาลัยแม่โจ้-ชุมพร",
"ระบบปรับอากาศรถไฟฟ้าขนาด ๒ ที่นั่ง",
"สังคม"])

In [121]:
Xtest_tf = tf_transformer.transform(Xtest_count)

In [122]:
clf.predict(Xtest_tf)

array(['การแพทย์', 'เกษตร', 'เกษตร', 'วิทยาศาสตร์', 'เกษตร'], dtype='<U11')

In [131]:
import joblib

In [132]:
joblib.dump(clf, 'Research_group_model.pkl')

['Research_group_model.pkl']